yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('group/<slug:slug>/', views.GroupView.as_view(), name='group_list'),
    path(
        'profile/<str:username>/',
        views.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.AddCommentView.as_view(),
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.PostEditView.as_view(),
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/',
        views.PostDetailView.as_view(),
        name='post_detail'
    ),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('follow/', views.FollowIndexView.as_view(), name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.ProfileFollowView.as_view(),
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.ProfileUnFollowView.as_view(),
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from core.models import CreatedModel
from .constants import CUT_STR_POST

User = get_user_model()


class Group(models.Model):
    """
    Group model for groups with unique url.
    """
    title = models.CharField('название группы', max_length=200)
    slug = models.SlugField(
        'адрес группы',
        unique=True,
    )
    description = models.TextField('описание группы', max_length=500)

    def __str__(self):
        return self.title


class Post(CreatedModel):
    """
    Posts. Main thing this project is about.
    """
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='автор поста',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='группа поста',
        help_text='Выберите группу',
    )
    image = models.ImageField(
        'Picture',
        upload_to='posts/',
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:CUT_STR_POST]


class Comment(CreatedModel):
    """Comments to the posts."""
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='связанный пост',
        help_text='Выберите пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='автор комментария',
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    """Модель подписчиков."""
    # Я все еще считаю что OneToOne и ManyToMany тут смотрелись бы лучше.
    # Один автор, одна подписка, одна запись в базе.
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='писака',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique following'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'text',
            'group',
            'image',
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'text',
        ]

yatube/posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import (
    FormView,
    ListView,
    DetailView,
    UpdateView,
    CreateView
)
from django.urls import reverse

from .constants import PAGES
from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm


def get_author(username):
    return get_object_or_404(User, username=username)


class IndexView(ListView):
    """Index page."""
    queryset = Post.objects.select_related('group', 'author')
    template_name = 'posts/index.html'
    paginate_by = PAGES


class GroupView(ListView):
    """Group list page."""
    template_name = 'posts/group_list.html'
    paginate_by = PAGES

    def get_group(self):
        return get_object_or_404(Group, slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['group'] = self.get_group()

        return context

    def get_queryset(self):
        group = self.get_group()
        posts = group.posts.select_related('author')

        return posts


class ProfileView(ListView):
    """Profile page."""
    template_name = 'posts/profile.html'
    paginate_by = PAGES

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = get_author(self.kwargs['username'])
        user = self.request.user
        context['author'] = author
        if user.is_authenticated and user != author:
            context['following'] = Follow.objects.filter(
                author=author,
                user=user
            ).exists()

        return context

    def get_queryset(self):
        author = get_author(self.kwargs['username'])
        posts = author.posts.all()

        return posts


class PostDetailView(DetailView):
    """Post detail page."""
    template_name = 'posts/post_detail.html'

    def get_object(self):
        post = get_object_or_404(
            Post.objects.select_related('author', 'group'),
            pk=self.kwargs.get('post_id')
        )

        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.get_object().comments.all()
        context['form'] = CommentForm()

        return context


class PostCreateView(LoginRequiredMixin, FormView):
    """Post creating form."""
    template_name = 'posts/post_create.html'
    form_class = PostForm

    def get_success_url(self):
        return reverse(
            'posts:profile',
            kwargs={'username': self.request.user}
        )

    def form_valid(self, form):
        completed_form = form.save(commit=False)
        completed_form.author = self.request.user
        completed_form.save()

        return super().form_valid(form)


class PostEditView(LoginRequiredMixin, UpdateView):
    """Post editing form."""
    template_name = 'posts/post_create.html'
    model = Post
    form_class = PostForm
    pk_url_kwarg = 'post_id'

    def get_post(self):
        return get_object_or_404(Post, pk=self.kwargs.get('post_id'))

    def get_success_url(self):
        return reverse(
            'posts:post_detail',
            kwargs={'post_id': self.kwargs.get('post_id')}
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = True

        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:

            return self.handle_no_permission()

        if request.user != self.get_post().author:
            return redirect(
                'posts:post_detail',
                self.kwargs.get('post_id')
            )

        return super().dispatch(request, *args, **kwargs)


class AddCommentView(LoginRequiredMixin, FormView):
    """Comment adding form. Form is in context on post detail page."""
    http_method_names = ['post']
    form_class = CommentForm

    def form_valid(self, form):
        completed_form = form.save(commit=False)
        completed_form.author = self.request.user
        completed_form.post = get_object_or_404(
            Post,
            pk=self.kwargs.get('post_id')
        )
        completed_form.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            'posts:post_detail',
            kwargs={'post_id': self.kwargs.get('post_id')}
        )


class FollowIndexView(LoginRequiredMixin, ListView):
    """Posts of followed authors."""
    template_name = 'posts/follow.html'
    paginate_by = PAGES

    def get_queryset(self):
        posts = Post.objects.filter(author__following__user=self.request.user)

        return posts


class ProfileFollowView(LoginRequiredMixin, CreateView):
    """Creating follow table query."""
    def get(self, request, *args, **kwargs):
        author = get_author(self.kwargs['username'])
        user = request.user
        # Is there a way to check this on model level?
        if author != user:
            Follow.objects.get_or_create(author=author, user=user)

        return redirect(
            reverse(
                'posts:profile',
                kwargs={'username': self.kwargs['username']}
            )
        )


class ProfileUnFollowView(LoginRequiredMixin, CreateView):
    """Deleting follow table query."""
    def get(self, request, *args, **kwargs):
        author = get_author(self.kwargs['username'])
        user = request.user
        Follow.objects.filter(author=author, user=user).delete()

        return redirect(
            reverse(
                'posts:profile',
                kwargs={'username': self.kwargs['username']}
            )
        )

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
    Мои подписки
{% endblock %}
{% load cache %}
{% block content %}
<h1>Мои подписки</h1>
{# {% cache 20 'follow_page' page_obj.number %} #}
{% for post in page_obj %}
  {% include 'posts/includes/card.html' %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{# {% endcache %} #}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
    Записи сообщества {{ group.title }}
{% endblock %}
{% load thumbnail %}
{% block content %}
<h1>{{ group.title }}</h1>
<p>{{ group.description }}</p>
{% for post in page_obj %}
  {% include 'posts/includes/card.html' %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
    Последние обновления на сайте
{% endblock %}
{% load cache %}
{% block content %}
<h1>Последние обновления на сайте</h1>
{% cache 20 'index_page' page_obj.number %}
{% for post in page_obj %}
  {% include 'posts/includes/card.html' %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endcache %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
  Редактировать
  {% else %}
  Новый пост
{% endif %}
{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать
            {% else %}
            Новая запись
          {% endif %}
        </div>
        <div class="card-body">
          {% include 'includes/form_error.html' %}
          <form method="post" enctype="multipart/form-data" action="
          {% if is_edit %}
          {% url 'posts:post_edit' form.instance.pk %}
          {% else %}
          {% url 'posts:post_create' %}
          {% endif %}
          ">
          {% csrf_token %}
          {% include 'includes/form_fields.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
              Сохранить
              {% else %}
              Отправить
              {% endif %}
            </button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% load thumbnail %}
{% block content %}
<article>
<div class="row">
<aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
    <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }} 
    </li>
    {% if post.group %}
    <li class="list-group-item">
        Группа: {{ post.group.title }} 
        <br>
        <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы
        </a>
    </li>
    {% endif %}
    <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  <span >{{ post.author.posts.count }}</span>
    </li>
    <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author.username %}">
        все посты пользователя
        </a>
    </li>
    </ul>
</aside>
<aside class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {{ post.text|linebreaksbr }}<br>
    {% if post.author ==  request.user %}
    <a href="{% url 'posts:post_edit' post.pk %}">редактировать</a>
    {% endif %}
    {% include 'posts/includes/comment_form.html'%}
    {% for comment in comments %}
    <div class="media mb-4">
        <div class="media-body">
        <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
            {{ comment.author.get_full_name }}
            </a>
            <p style="float: right; display: inline">
            {{ comment.created }}
            </p>
        </h5>
            <p style="overflow-wrap:break-word">
            {{ comment.text }}
            </p>
        </div>
    </div>
    {% endfor %}
</aside>
</div>
</article>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %} 
  
{% block title %}
Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% load thumbnail %}
{% block content %}
{% include 'posts/includes/follow_button.html' %}
{% for post in page_obj %}
    {% include 'posts/includes/card.html' %}
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock  %}